version: '3'
services:
  mmorpg_apache:
    image: pankiev/mmorpg_apache
    container_name: mmorpg_apache
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./app:/usr/local/apache2/htdocs/app/
    
      
    
